#!/bin/bash

### BEGIN INIT INFO
# Provides:          energy-monitoring-with-graphite
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts the daemons that collect energy data and feed it to Graphite
# Description:       Starts the daemons that collect energy data and feed it to Graphite. Supported daemons are dsmr, Nest, OpenWeathermap and system
### END INIT INFO

# Change the next 3 lines to suit where you install your script and what you want to call it
DIR=/home/data/energy-monitoring-with-graphite
DAEMONS=("dsmr" "Nest" "OpenWeatherMap" "system")

n=0
for x in "${DAEMONS[@]}"
do
	DAEMON_EXEC[$n]="$DIR/${DAEMONS[$n]}/${DAEMONS[$n]}.py"
	DAEMON_NAME[$n]="energy-monitoring-with-graphite-${DAEMONS[$n]}"
	# The process ID of the script when it runs is stored here:
	PIDFILE[$n]="/var/run/${DAEMONS[$n]}.pid"
	n=$((n+1))
done

# Add any command line options for your daemon here
DAEMON_OPTS=""

# This next line determines what user the script runs as.
# Root generally not recommended but necessary if you are using the Raspberry Pi GPIO from Python.
DAEMON_USER=root


. /lib/lsb/init-functions

do_start () {
    log_daemon_msg "Starting system ${DAEMON_NAME[$1]} daemon"
    start-stop-daemon --start --background --pidfile ${PIDFILE[$n]} --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas ${DAEMON_EXEC[$n]} -- $DAEMON_OPTS
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping system ${DAEMON_NAME[$1]} daemon"
    start-stop-daemon --stop --pidfile ${PIDFILE[$1]} --retry 10
    log_end_msg $?
}

case "$1" in

    start|stop)
	n=0
	for x in "${DAEMONS[@]}"
	do
        	do_${1} $n
		n=$((n+1))
	done
        ;;

    restart|reload|force-reload)
	n=0
	for x in "${DAEMONS[@]}"
	do
		do_stop $n
		do_start $n
		n=$((n+1))
	done
        ;;

    status)
	n=0
	for x in "${DAEMONS[@]}"
	do
		do_stop $n
		do_start $n
        	status_of_proc "$DAEMON_NAME" "$DAEMON_EXEC" && exit 0 || exit $?
		n=$((n+1))
	done
        ;;

    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0
